# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://levi-batkin.github.io"
baseurl: "/kittenscraft"
siteIcon: /media/android-chrome-192x192.png
siteYear: 2021
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: Kittens Craft
serverDescription: Kittens Craft is the best Minecraft network dedicated to cats, we revolve around cats to bring you an amazing Minecraft experience for all!
serverIP: play.kittenscraft.com
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/Bd2HEHA9xf
discordServerID: 898633594434641920
discordChannelID: 898633914179022868


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Server Map
#     url: map
#     newtab: true
#   - name: Screenshots
#     url: screenshots
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
